# Verde Tech
[main]
font=FiraMono Nerd Font:size=12
terminal=alacritty -e
prompt="  "
icon-theme=Colloid-Green-Everforest-Dark
width=40
lines=10
horizontal-pad=24
vertical-pad=16
inner-pad=8
line-height=22
layer=overlay

[colors]
background=0d1310e6
text=cfdcd4ff
prompt=6cc196ff
input=eef4f0ff
match=6cc196ff
selection=2b3d33ff
selection-text=eef4f0ff
selection-match=8fd3aeff
border=6cc196ff

[border]
width=2
radius=12
